#
# Copyright © 2010-2019 OddSource Code (license@oddsource.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM openjdk:11-jdk-stretch

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y gcc g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN cd /opt && \
    wget https://www-us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz && \
    tar -xzvf apache-maven-3.6.0-bin.tar.gz && \
    rm apache-maven-3.6.0-bin.tar.gz && \
    ln -s /opt/apache-maven-3.6.0/bin/mvn /usr/local/bin/mvn && \
    mvn --version

WORKDIR /srv/oddsource/raw-sockets/
COPY . /srv/oddsource/raw-sockets/
RUN rm -rf /srv/oddsource/raw-sockets/target \
    /srv/oddsource/raw-sockets/source/production/resources/io/oddsource/java/net/socket/*.so \
    /srv/oddsource/raw-sockets/source/production/resources/io/oddsource/java/net/socket/*.dylib \
    /srv/oddsource/raw-sockets/source/production/resources/io/oddsource/java/net/socket/*.dll
