/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_oddsource_java_net_socket_Constants */

#ifndef _Included_io_oddsource_java_net_socket_Constants
#define _Included_io_oddsource_java_net_socket_Constants
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_oddsource_java_net_socket_Constants
 * Method:    registerNumericConstant
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_oddsource_java_net_socket_Constants_registerNumericConstant
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
